// Generated by CoffeeScript 1.8.0
(function() {
  var MessageHandler;

  MessageHandler = (function() {
    MessageHandler.prototype.lastMessages = {};

    function MessageHandler(conn) {
      this.conn = conn;
    }

    MessageHandler.prototype.broadcast = function(type, data, connections) {
      var senderId;
      if (JSON.stringify(data) === JSON.stringify(this.lastMessages[this.conn.sessionId])) {
        return;
      }
      this.lastMessages[this.conn.sessionId] = data;
      senderId = this.conn.getId();
      return connections.forEach(function(conn) {
        var id;
        id = conn.getId();
        if (senderId !== id) {
          return conn.send(JSON.stringify(data));
        }
      });
    };

    MessageHandler.prototype.handle = function(data, connections) {
      var _ref;
      if ((_ref = data.type) === 'open' || _ref === 'close' || _ref === 'save' || _ref === 'select' || _ref === 'cursor') {
        return this.broadcast(data.type, data, connections);
      }
    };

    return MessageHandler;

  })();

  module.exports = MessageHandler;

}).call(this);
